controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    stretch_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    servo_controller:
      type: joint_trajectory_controller/JointTrajectoryController

stretch_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
    joints:
      - joint_lift
      - joint_arm_l3
      - joint_arm_l2
      - joint_arm_l1
      - joint_arm_l0
      - joint_wrist_yaw
      - joint_head_pan
      - joint_head_tilt
      - joint_gripper_finger_left
      - joint_gripper_finger_right
      - position

servo_controller:
  ros__parameters:
    joints:
      - joint_arm_l0
      - joint_arm_l1
      - joint_arm_l2
      - joint_arm_l3
      - joint_lift
      - joint_wrist_yaw
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    command_joints:
      - joint_arm_l0
      - joint_arm_l1
      - joint_arm_l2
      - joint_arm_l3
      - joint_lift
      - joint_wrist_yaw
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
      joint_arm_l0:
        goal: 0.05
      joint_arm_l1:
        goal: 0.05
      joint_arm_l2:
        goal: 0.05
      joint_arm_l3:
        goal: 0.05
      joint_lift:
        goal: 0.05
      joint_wrist_yaw:
        goal: 0.05
