controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    stretch_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    servo_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    stretch_base_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_drive_controller:
      type: picknik_diff_drive_controller/DiffDriveController

stretch_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
    joints:
      - joint_lift
      - joint_arm_l3
      - joint_arm_l2
      - joint_arm_l1
      - joint_arm_l0
      - joint_wrist_yaw
      - joint_head_pan
      - joint_head_tilt
      - joint_gripper_finger_left
      - joint_gripper_finger_right

stretch_base_controller:
  ros__parameters:
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
    open_loop_control: true # disables PID
    allow_integration_in_goal_trajectories: true
    joints:
      - position/x
      - position/y
      - position/theta
    command_joints:
      - diff_drive_controller/x
      - diff_drive_controller/y
      - diff_drive_controller/theta

# Controller configuration for HelloRobot Stretch RE1
# See https://docs.hello-robot.com/0.2/stretch-hardware-guides/docs/hardware_guide_re1/#base
diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["joint_left_wheel"]
    right_wheel_names: ["joint_right_wheel"]

    wheel_separation: 0.3 # estimate! (340mm - 2x20mm wheel width)
    wheels_per_side: 1
    wheel_radius: 0.0508

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits, should match MoveIt's default_joint_limits.yaml
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.42
    linear.x.max_acceleration: 0.2
    linear.x.max_jerk: 0.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.42
    angular.z.max_acceleration: 0.2
    angular.z.max_jerk: 0.0
